### ISSUE TITLE
NameError: global name 'origsigwinchhandler' is not defined

### ISSUE THREAD

**Issue by jepler** [andrewshadura/git-crecord#14]
Steps to reproduce:
 1. Make any change, e.g., 'echo "I'm a little teapot">>README.rst
 2. git-crecord
 3. type 's', then 'y'
Result: A traceback on the terminal, and the changes are not staged.  The full traceback reads:
```Traceback (most recent call last):
  File "./git-crecord", line 4, in <module>
    main()
  File "/home/jepler/src/git-crecord/git_crecord/main.py", line 185, in main
    crecord_core.dorecord(ui, repo, None, **(opts))
  File "/home/jepler/src/git-crecord/git_crecord/crecord_core.py", line 202, in dorecord
    return recordfunc(ui, repo, "", None, opts)
  File "/home/jepler/src/git-crecord/git_crecord/crecord_core.py", line 71, in recordfunc
    chunk_selector.chunkselector, ui)
  File "/home/jepler/src/git-crecord/git_crecord/crpatch.py", line 687, in filterpatch
    chunkselector(opts, headers, ui)
  File "/home/jepler/src/git-crecord/git_crecord/chunk_selector.py", line 71, in chunkselector
    curses.wrapper(chunkselector.main, opts)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/jepler/src/git-crecord/git_crecord/chunk_selector.py", line 1122, in main
    return self._main(stdscr)
  File "/home/jepler/src/git-crecord/git_crecord/chunk_selector.py", line 1185, in _main
    signal.signal(signal.SIGWINCH, origsigwinchhandler)
NameError: global name 'origsigwinchhandler' is not defined
```

Tested at commit ec11e17bbfdec9ebbb641b665f9f8c85a28cc529

**Comment by andrewshadura** [comment]
Sorry, I forgot to push the fix (e299070)
