### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 38: ordinal not in range(128)

### ISSUE THREAD

**Issue by carun** [andrewshadura/git-crecord#19]
Happens when trying to toggle a hunk fold

Changeset: 9d83975 on master

```py
Traceback (most recent call last):
  File "/usr/bin/git-crecord", line 9, in <module>
    load_entry_point('git-crecord==20161226.0', 'console_scripts', 'git-crecord')()
  File "/usr/lib/python2.7/site-packages/git_crecord/main.py", line 193, in main
    crecord_core.dorecord(ui, repo, None, **(opts))
  File "/usr/lib/python2.7/site-packages/git_crecord/crecord_core.py", line 190, in dorecord
    return recordfunc(ui, repo, "", None, opts)
  File "/usr/lib/python2.7/site-packages/git_crecord/crecord_core.py", line 71, in recordfunc
    chunk_selector.chunkselector, ui)
  File "/usr/lib/python2.7/site-packages/git_crecord/crpatch.py", line 686, in filterpatch
    chunkselector(opts, headers, ui)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 71, in chunkselector
    curses.wrapper(chunkselector.main, opts)
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 1126, in main
    return self._main(stdscr)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 1179, in _main
    self.updatescreen()
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 592, in updatescreen
    self.printitem()
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 762, in printitem
    towin=towin)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 808, in __printitem
    recursechildren, outstr, towin)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 816, in __printitem
    recursechildren, outstr, towin)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 825, in __printitem
    recursechildren, outstr, towin)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 831, in __printitem
    towin=towin))
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 745, in printhunkchangedline
    towin=towin, showwhtspc=True)
  File "/usr/lib/python2.7/site-packages/git_crecord/chunk_selector.py", line 510, in printstring
    window.addstr(text, colorpair)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 38: ordinal not in range(128)
```

**Comment by carun** [comment]
Tested on RHEL 7.4, git bisect shows the following cset.

```
29-03-2019 18:42:28 arun-desk-r7 ~/code/git-crecord
$ git bisect good
b4fb91adbe7c889f75de5fe990bd9fd2589e9ef4 is the first bad commit
commit b4fb91adbe7c889f75de5fe990bd9fd2589e9ef4
Author: Andrej Shadura <andrew@shadura.me>
Date:   Tue Jul 3 16:17:17 2018 +0200

    cStringIO -> io

:040000 040000 a8f8ab5ec76cc84098adcdb381e19a9fbe13991f 8ec85ec4efad2060c599f5717cd8e34960389d19 M      git_crecord
29-03-2019 18:42:37 arun-desk-r7 ~/code/git-crecord
$
```

**Comment by carun** [comment]
My RHEL 7.4 has Python 2 and not Python 3. So this is not an issue.
