### ISSUE TITLE
TypeError: togglefolded() got an unexpected keyword argument 'foldParent'

### ISSUE THREAD

**Issue by carun** [andrewshadura/git-crecord#20]
```
$ git crecord
Traceback (most recent call last):
  File "/home/arun/.bin/git-crecord", line 4, in <module>
    main()
  File "/home/arun/code/git-crecord/git_crecord/main.py", line 193, in main
    crecord_core.dorecord(ui, repo, None, **(opts))
  File "/home/arun/code/git-crecord/git_crecord/crecord_core.py", line 190, in dorecord
    return recordfunc(ui, repo, "", None, opts)
  File "/home/arun/code/git-crecord/git_crecord/crecord_core.py", line 71, in recordfunc
    chunk_selector.chunkselector, ui)
  File "/home/arun/code/git-crecord/git_crecord/crpatch.py", line 686, in filterpatch
    chunkselector(opts, headers, ui)
  File "/home/arun/code/git-crecord/git_crecord/chunk_selector.py", line 71, in chunkselector
    curses.wrapper(chunkselector.main, opts)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/arun/code/git-crecord/git_crecord/chunk_selector.py", line 1126, in main
    return self._main(stdscr)
  File "/home/arun/code/git-crecord/git_crecord/chunk_selector.py", line 1187, in _main
    if self.handlekeypressed(keypressed):
  File "/home/arun/code/git-crecord/git_crecord/chunk_selector.py", line 1104, in handlekeypressed
    self.togglefolded(foldParent=True)
TypeError: togglefolded() got an unexpected keyword argument 'foldParent'
```

**Comment by carun** [comment]
This PR commit should fix it.
