### ISSUE TITLE
git submodule add followed by git crecord fails with IsADirectoryError

### ISSUE THREAD

**Issue by carun** [andrewshadura/git-crecord#27]
```
2020-08-06 15:38:07 ~/code/aim-es-v3 (neoface-license-deps)
$ git submodule add --name neoface-license-dependencies ssh://git@git-fusion.spherecom.com:7999/did/neoface-license-dependencies.git docker/neoface-license-dependencies

2020-08-06 15:43:07 ~/code/aim-es-v3 (neoface-license-deps)
$ git status
On branch feature/neoface-license-deps
Your branch is up to date with 'origin/feature/neoface-license-deps'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   .gitmodules
        new file:   docker/neoface-license-dependencies

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   docker/neoface-license-dependencies (untracked content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        build/

2020-08-06 15:38:20 ~/code/aim-es-v3 (neoface-license-deps)
$ git crecord
Traceback (most recent call last):
  File "/usr/local/bin/git-crecord", line 11, in <module>
    load_entry_point('git-crecord==20161226.0', 'console_scripts', 'git-crecord')()
  File "/usr/local/lib/python3.6/dist-packages/git_crecord-20161226.0-py3.6.egg/git_crecord/main.py", line 193, in main
  File "/usr/local/lib/python3.6/dist-packages/git_crecord-20161226.0-py3.6.egg/git_crecord/crecord_core.py", line 190, in dorecord
  File "/usr/local/lib/python3.6/dist-packages/git_crecord-20161226.0-py3.6.egg/git_crecord/crecord_core.py", line 111, in recordfunc
  File "/usr/local/lib/python3.6/dist-packages/git_crecord-20161226.0-py3.6.egg/git_crecord/util.py", line 97, in copyfile
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/home/arun/code/aim-es-v3/docker/neoface-license-dependencies'
2020-08-06 15:38:32 ~/code/aim-es-v3 (neoface-license-deps)
$
```

**Comment by andrewshadura** [comment]
Thanks! I’ll try to find time to investage this.

**Comment by andrewshadura** [comment]
By the way, have you tried the latest Git version? It shouldn’t make any difference, but just to be sure.

**Comment by andrewshadura** [comment]
I’ve added a change which should enable committing submodules, but it still prints a (harmless) error.
I will look into a proper fix later.
