### ISSUE TITLE
Patch error with `noprefix = true` in gitconfig

### ISSUE THREAD

**Issue by carun** [andrewshadura/git-crecord#57]
![image](https://github.com/user-attachments/assets/0c302085-725f-4b64-9af9-0be06b4486c8)

**Comment by andrewshadura** [comment]
Thanks, I think I have a fix for this one.

**Comment by andrewshadura** [comment]
Can you please test commit fe8f08e (branch `fix-57`)?

**Comment by carun** [comment]
Thanks @andrewshadura I'm using crecord via pip now. How do I use the custom version, could you please show me?

```
$ pip list | grep git-crecord
git-crecord         20230226.0
```

**Comment by carun** [comment]
```
$ git cr
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arun/.local/bin/git-crecord", line 4, in <module>
    main()
  File "/home/arun/git-crecord/git_crecord/main.py", line 183, in main
    version = importlib.metadata.version("git-crecord")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 889, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for git-crecord
```
