### ISSUE TITLE
Install problem from pip

### ISSUE THREAD

**Issue by pklapperich** [andrewshadura/git-crecord#9]
I haven't worked much with setup.py, but when I try to install using python2-pip (installed as pip2 on my system) I get an error about absolute paths. I'm not sure if the version on pypi is just out of date (and should be updated) or if setup.py needs to be updated to pass pypi's checks, but this seemed like an OK place to inform you of the problem:

```
$ sudo pip2 install git-crecord
Collecting git-crecord
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/87/aa/b67aa4b084e57bc00a5a1d4b07a4dc037136ca4b3b51563ea8dbd5d1e752/git-crecord-20161226.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 1.8MB/s 
Requirement already satisfied: docutils>=0.12 in /usr/lib/python2.7/site-packages (from git-crecord)
Installing collected packages: git-crecord
  Running setup.py install for git-crecord ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-PJITrz/git-crecord/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-FlovhE-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/git_crecord
    copying git_crecord/util.py -> build/lib/git_crecord
    copying git_crecord/crecord_core.py -> build/lib/git_crecord
    copying git_crecord/__init__.py -> build/lib/git_crecord
    copying git_crecord/gitrepo.py -> build/lib/git_crecord
    copying git_crecord/main.py -> build/lib/git_crecord
    copying git_crecord/chunk_selector.py -> build/lib/git_crecord
    copying git_crecord/crpatch.py -> build/lib/git_crecord
    copying git_crecord/encoding.py -> build/lib/git_crecord
    running egg_info
    writing requirements to git_crecord.egg-info/requires.txt
    writing git_crecord.egg-info/PKG-INFO
    writing top-level names to git_crecord.egg-info/top_level.txt
    writing dependency_links to git_crecord.egg-info/dependency_links.txt
    writing entry points to git_crecord.egg-info/entry_points.txt
    reading manifest file 'git_crecord.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'git_crecord.egg-info/SOURCES.txt'
    error: Error: setup script specifies an absolute path:
    
        /tmp/pip-build-PJITrz/git-crecord/README.rst
    
    setup() arguments must *always* be /-separated paths relative to the
    setup.py directory, *never* absolute paths.
```

**Comment by pklapperich** [comment]
Also `python2 setup.py install` does not work, which is maybe related. `./setup.py install` does work, but I think the first way should also work.

**Comment by kuoe0** [comment]
I got another problem while installing from pip.

```
$ pip3 install git-crecord
Collecting git-crecord
  Downloading https://files.pythonhosted.org/packages/87/aa/b67aa4b084e57bc00a5a1d4b07a4dc037136ca4b3b51563ea8dbd5d1e752/git-crecord-20161226.0.tar.gz (77kB)
    100% |████████████████████████████████| 81kB 1.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jqmt5bv8/git-crecord/setup.py", line 5, in <module>
        import docutils.core
    ModuleNotFoundError: No module named 'docutils'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jqmt5bv8/git-crecord/
```

But this can be fixed after `docutils` is installed. And then, there is another problem that comes out.

```
$ pip3 install git-crecord
Collecting git-crecord
  Using cached https://files.pythonhosted.org/packages/87/aa/b67aa4b084e57bc00a5a1d4b07a4dc037136ca4b3b51563ea8dbd5d1e752/git-crecord-20161226.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_4jg7dvw/git-crecord/setup.py", line 62, in <module>
        ] + man_files('git-*.rst'),
    TypeError: can only concatenate list (not "map") to list
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_4jg7dvw/git-crecord/
```

Also tried with `pip2` and got the sam error.

**Comment by andrewshadura** [comment]
Could you please try running `pip install https://github.com/andrewshadura/git-crecord`?

**Comment by kuoe0** [comment]
Oh, cool! I don't `pip` support to install from URL. BTW, the command should be `pip install git+https://github.com/andrewshadura/git-crecord`. Thanks!
